# fly.toml app configuration file generated for materbot on 2024-10-25T23:16:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "materbot"
primary_region = "mad"

[env]
  PORT="8080"
  BOT_LANG="es"
  LOG_LEVEL="debug"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  
